Repository City-of-Helsinki/hel-fi-drupal-grants, pull requests merged in 2023-10, with the labels that each got.

#593 AU-1348: Kasvatus ja koulutus: toiminta-avustushakemus // ID 52
  conf/cmi/grants_metadata.settings.yml
  conf/cmi/language/en/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
  conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
  conf/cmi/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
  public/modules/custom/grants_budget_components/src/Element/GrantsBudgetCostStatic.php
  public/modules/custom/grants_budget_components/src/Element/GrantsBudgetIncomeStatic.php
  public/modules/custom/grants_budget_components/src/GrantsBudgetComponentService.php
  public/modules/custom/grants_budget_components/translations/fi.po
  public/modules/custom/grants_budget_components/translations/sv.po
  public/modules/custom/grants_metadata/src/AtvSchema.php
  public/modules/custom/grants_metadata/src/Plugin/DataType/KaskoToimintaData.php
  public/modules/custom/grants_metadata/src/TypedData/Definition/KaskoToimintaDefinition.php
  public/modules/custom/grants_place_of_operation/src/Element/PlaceOfOperationComposite.php
  public/modules/custom/grants_place_of_operation/src/Plugin/DataType/PlaceOfOperationData.php
  public/modules/custom/grants_place_of_operation/src/TypedData/Definition/PlaceOfOperationDefinition.php
  public/themes/custom/hdbt_subtheme/dist/css/styles.min.css
  public/themes/custom/hdbt_subtheme/src/scss/components/webform/_form_elements.scss
Labels: Hakemuslomake

#818 feat: AU-1662 Budget components in print preview
  public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
Labels: UI

#820 AU-1703: Change size field to allow decimals and fix data types
  conf/cmi/grants_metadata.settings.yml
  public/modules/custom/grants_orienteering_map/src/Element/OrienteeringMapComposite.php
  public/modules/custom/grants_orienteering_map/src/TypedData/Definition/OrienteeringMapDefinition.php
Labels: Pending
