Repository City-of-Helsinki/hel-fi-drupal-grants, pull requests merged in 2023-09, with the labels that each got.

#696 fix: AU-1522, AU-1524 AU-1529: conf content changes
  conf/cmi/language/en/webform.webform.nuorisotoiminta_projektiavustush.yml
  conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml
  conf/cmi/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
  conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
  conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
Labels: UI

#701 fix: AU-1530: toiminta- ja tilankäyttö composite translations
  public/modules/custom/grants_club_section/src/Element/ClubSectionComposite.php
  public/modules/custom/grants_club_section/translations/fi.po
  public/modules/custom/grants_club_section/translations/sv.po
  public/modules/custom/grants_premises/src/Element/RentIncomeComposite.php
  public/modules/custom/grants_premises/translations/fi.po
  public/modules/custom/grants_premises/translations/sv.po
Labels: UI

#695 AU-1552: Remove delivered later / in other file from NUORISO forms
  conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
  conf/cmi/webform.webform.nuorisotoiminta_projektiavustush.yml
  conf/cmi/webform.webform.nuorlomaleir.yml
  public/modules/custom/grants_attachments/src/Element/GrantsAttachments.php
Labels: BE

#679 feat: AU-1486: Import webform configs from production
  composer.json
  composer.lock
  conf/cmi/core.extension.yml
  conf/cmi/jsonapi.settings.yml
  conf/cmi/jsonapi_extras.settings.yml
  conf/cmi/system.action.user_add_role_action.json_api_user.yml
  conf/cmi/system.action.user_remove_role_action.json_api_user.yml
  conf/cmi/user.role.ad_user.yml
  conf/cmi/user.role.admin.yml
  conf/cmi/user.role.content_producer.yml
  conf/cmi/user.role.content_producer_industry.yml
  conf/cmi/user.role.grants_admin.yml
  conf/cmi/user.role.grants_producer.yml
  conf/cmi/user.role.helsinkiprofiili.yml
  conf/cmi/user.role.json_api_user.yml
  conf/cmi/user.role.read_only.yml
  public/modules/custom/grants_webform_import/drush.services.yml
  public/modules/custom/grants_webform_import/grants_webform_import.services.yml
  public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
  public/modules/custom/grants_webform_import/src/Routing/JsonapiLimitingRouteSubscriber.php
Labels: BE

#648 AU-1305: Kaupunginkanslia, tyollisyyshakemus // ID 54
  conf/cmi/grants_metadata.settings.yml
  conf/cmi/language/en/webform.webform.kaupunginkanslia_tyollisyysavust.yml
  conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml
  conf/cmi/webform.webform.kaupunginkanslia_tyollisyysavust.yml
  public/modules/custom/grants_metadata/src/Plugin/DataType/TyollisyysavustusHakemusData.php
  public/modules/custom/grants_metadata/src/TypedData/Definition/TyollisyysavustusHakemusDefinition.php
Labels: Hakemuslomake

#723 fix: AU-1571: Fix too long swedish headlines
  conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml
  conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml
  conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml
  conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml
  conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
  conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml
  conf/cmi/language/sv/webform.webform.nuorlomaleir.yml
  conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
  conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml
  public/themes/custom/hdbt_subtheme/dist/css/styles.min.css
  public/themes/custom/hdbt_subtheme/src/scss/components/webform/_form_elements.scss
Labels: lowprio

#653 AU-1467: Asukasosallisuus: pienavustushakemus (ID 64)
  conf/cmi/grants_metadata.settings.yml
  conf/cmi/language/en/webform.webform.asukasosallisuus_pienavustushake.yml
  conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml
  conf/cmi/webform.webform.asukasosallisuus_pienavustushake.yml
  public/modules/custom/grants_handler/grants_handler.module
  public/modules/custom/grants_metadata/src/Plugin/DataType/AsukaPienaData.php
  public/modules/custom/grants_metadata/src/TypedData/Definition/AsukaPienaDefinition.php
  public/modules/custom/grants_metadata/src/TypedData/Definition/NuorisoProjektiDefinition.php
  tools/make/project/avustusasiointi.mk
Labels: Hakemuslomake

#601 AU-1317: Liikunta, Suunnistuskartta-avustushakemus // ID 58
  conf/cmi/core.extension.yml
  conf/cmi/grants_metadata.settings.yml
  conf/cmi/language/en/webform.webform.liikunta_suunnistuskartta_avustu.yml
  conf/cmi/language/sv/webform.webform.liikunta_suunnistuskartta_avustu.yml
  conf/cmi/webform.webform.liikunta_suunnistuskartta_avustu.yml
  public/modules/custom/grants_metadata/config/install/grants_metadata.settings.yml
  public/modules/custom/grants_metadata/src/Plugin/DataType/LiikuntaSuunnistusData.php
  public/modules/custom/grants_metadata/src/TypedData/Definition/LiikuntaSuunnistusDefinition.php
  public/modules/custom/grants_orienteering_map/grants_orienteering_map.info.yml
  public/modules/custom/grants_orienteering_map/grants_orienteering_map.module
  public/modules/custom/grants_orienteering_map/src/Element/OrienteeringMapComposite.php
  public/modules/custom/grants_orienteering_map/src/Plugin/DataType/OrienteeringMapData.php
  public/modules/custom/grants_orienteering_map/src/Plugin/WebformElement/OrienteeringMapComposite.php
  public/modules/custom/grants_orienteering_map/src/TypedData/Definition/OrienteeringMapDefinition.php
  public/modules/custom/grants_orienteering_map/templates/orienteering-map-composite.twig
  public/modules/custom/grants_orienteering_map/translations/fi.po
  public/modules/custom/grants_orienteering_map/translations/sv.po
  public/themes/custom/hdbt_subtheme/dist/css/styles.min.css
  public/themes/custom/hdbt_subtheme/src/scss/components/webform/_fieldset.scss
Labels: Hakemuslomake
