Repository City-of-Helsinki/hel-fi-drupal-grants, pull requests merged in 2023-08, with the labels that each got.

#686 fix: AU-1544: Create node revision on Webform config import
  public/modules/custom/grants_metadata/grants_metadata.module
Labels: BE

#683 fix/AU-1488: Added postal code checking to the grants premises component
  public/modules/custom/grants_premises/src/Element/PremisesComposite.php
  public/modules/custom/grants_premises/translations/fi.po
  public/modules/custom/grants_premises/translations/sv.po
Labels: UI, BE

#689 fix: AU-1485: change name of Nuorisotoimi to Nuorisotoiminta
  conf/cmi/grants_metadata.settings.yml
  conf/cmi/webform.webform.nuorlomaleir.yml
  public/modules/custom/grants_handler/config/install/webform.webform.nuorlomaleir.yml
  public/modules/custom/grants_metadata/config/install/grants_metadata.settings.yml
Labels: UI

#688 fix: AU-1469 Remove Double Tooltips from First Page Composites
  public/modules/custom/grants_handler/src/Element/BankAccountComposite.php
  public/modules/custom/grants_handler/src/Element/CommunityAddressComposite.php
Labels: UI
