Repository City-of-Helsinki/hel-fi-drupal-grants, pull requests merged in 2024-04, with the labels that each got.

#1316 feat: AU-2384: E2E, Implemented soft assertion for verifySubmit
  e2e/utils/form_helpers.ts
  e2e/utils/helpers.ts
  e2e/utils/validation_helpers.ts
Labels: e2e

#1319 feat: AU-2389: E2E, Changed the edit-acting-year field in every test to always be dynamic
  e2e/tests/forms/private_person_48.ts
  e2e/tests/forms/private_person_64.ts
  e2e/tests/forms/registered_community_29.ts
  e2e/tests/forms/registered_community_48.ts
  e2e/tests/forms/registered_community_51.ts
  e2e/tests/forms/registered_community_52.ts
  e2e/tests/forms/registered_community_53.ts
  e2e/tests/forms/registered_community_54.ts
  e2e/tests/forms/registered_community_56.ts
  e2e/tests/forms/registered_community_57.ts
  e2e/tests/forms/registered_community_58.ts
  e2e/tests/forms/registered_community_60.ts
  e2e/tests/forms/registered_community_61.ts
  e2e/tests/forms/registered_community_62.ts
  e2e/tests/forms/registered_community_63.ts
  e2e/tests/forms/registered_community_64.ts
  e2e/tests/forms/registered_community_65.ts
  e2e/tests/forms/registered_community_66.ts
  e2e/tests/forms/registered_community_68.ts
  e2e/tests/forms/registered_community_69.ts
  e2e/tests/forms/unregistered_community_48.ts
  e2e/tests/forms/unregistered_community_62.ts
  e2e/tests/forms/unregistered_community_64.ts
  e2e/tests/forms/unregistered_community_65.ts
  e2e/tests/forms/unregistered_community_66.ts
  e2e/tests/forms/unregistered_community_69.ts
  e2e/utils/data/application/application_data_29.ts
  e2e/utils/data/application/application_data_48.ts
  e2e/utils/data/application/application_data_51.ts
  e2e/utils/data/application/application_data_52.ts
  e2e/utils/data/application/application_data_53.ts
  e2e/utils/data/application/application_data_54.ts
  e2e/utils/data/application/application_data_56.ts
  e2e/utils/data/application/application_data_57.ts
  e2e/utils/data/application/application_data_58.ts
  e2e/utils/data/application/application_data_60.ts
  e2e/utils/data/application/application_data_61.ts
  e2e/utils/data/application/application_data_62.ts
  e2e/utils/data/application/application_data_63.ts
  e2e/utils/data/application/application_data_64.ts
  e2e/utils/data/application/application_data_65.ts
  e2e/utils/data/application/application_data_66.ts
  e2e/utils/data/application/application_data_68.ts
  e2e/utils/data/application/application_data_69.ts
Labels: e2e

#1314 fix: AU-2366: Fix application search card lead-in text display
  public/themes/custom/hdbt_subtheme/templates/field/field--field-lead-in.html.twig
Labels: UI

#1317 AU-2343: Nuortoimpalkka input masks to euro fields
  conf/cmi/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
  public/modules/custom/grants_handler/grants_handler.module
  public/modules/custom/grants_metadata/src/InputmaskHandler.php
Labels: UI

#1322 feat: AU-2373: Fix notice during application copy. Add event to copied application
  public/modules/custom/grants_attachments/src/AttachmentHandler.php
  public/modules/custom/grants_handler/src/EventsService.php
  public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php
Labels: BE

#1327 fix: AU-2395: Hide buttons that link from TPR to the page we are already on.
  public/themes/custom/hdbt_subtheme/dist/css/styles.min.css
  public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
  public/themes/custom/hdbt_subtheme/src/scss/layout/_node--service.scss
Labels: UI

#1326 fix: AU-2396: First 74 phpstan errors
  public/modules/custom/grants_handler/src/ApplicationHandler.php
  public/modules/custom/grants_metadata/src/Controller/ApplicationStatusCheckController.php
  public/modules/custom/grants_metadata/src/GrantsConverterService.php
  public/modules/custom/grants_metadata/src/TypedDataToDocumentContentWithWebform.php
  public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
  public/modules/custom/grants_oma_asiointi/src/Controller/GrantsOmaAsiointiController.php
  public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php
  public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiBlock.php
  public/modules/custom/grants_oma_asiointi/src/Plugin/Block/OmaAsiointiHeroBlock.php
  public/modules/custom/grants_performance_tests/grants_performance_tests.module
  public/modules/custom/grants_place_of_operation/src/PlaceOfOperationService.php
  public/modules/custom/grants_premises/src/GrantsPremisesService.php
  public/modules/custom/grants_profile/grants_profile.module
  public/modules/custom/grants_profile/src/Controller/GrantsProfileController.php
  public/modules/custom/grants_profile/src/Form/AddressDeleteConfirmForm.php
  public/modules/custom/grants_profile/src/Form/BankAccountDeleteConfirmForm.php
  public/modules/custom/grants_profile/src/Form/GrantsProfileFormBase.php
  public/modules/custom/grants_profile/src/Form/GrantsProfileFormPrivatePerson.php
  public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php
  public/modules/custom/grants_profile/src/Form/GrantsProfileFormUnregisteredCommunity.php
  public/modules/custom/grants_profile/src/Form/MunicipalitySettingsForm.php
  public/modules/custom/grants_profile/src/Form/OfficialDeleteConfirmForm.php
  public/modules/custom/grants_profile/src/GrantsProfileCache.php
  public/modules/custom/grants_profile/src/GrantsProfileService.php
  public/modules/custom/grants_profile/src/MunicipalityService.php
  public/modules/custom/grants_profile/src/Plugin/Block/ProfileBlock.php
  public/modules/custom/grants_profile/src/ProfileConnector.php
  public/modules/custom/grants_profile/src/UserRedirect.php
  public/modules/custom/grants_test_base/src/Kernel/GrantsKernelTestBase.php
  public/modules/custom/grants_test_base/src/MockSession.php
  public/modules/custom/grants_webform_import/src/Commands/WebformImportCommands.php
  public/modules/custom/grants_webform_print/src/Controller/GrantsWebformPrintController.php
  public/modules/custom/grants_webform_print/src/Controller/GrantsWebformSubmissionPrintController.php
  public/modules/custom/grants_webform_summation_field/src/Plugin/WebformElement/GrantsWebformSummationField.php
  public/themes/custom/hdbt_subtheme/hdbt_subtheme.theme
Labels: BE

#1321 AU-2381: Add event when resending applications via admin ui
  public/modules/custom/grants_admin_applications/src/Form/AtvFormBase.php
  public/modules/custom/grants_handler/src/EventsService.php
  public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
Labels: BE

#1332 fix: AU-2452: Focus indicators to stepper and readonly fields
  public/themes/custom/hdbt_subtheme/dist/css/styles.min.css
  public/themes/custom/hdbt_subtheme/src/scss/components/webform/_form_elements.scss
  public/themes/custom/hdbt_subtheme/src/scss/components/webform/_progress_tracker.scss
Labels: UI

#1331 fix: AU-2428: Fix empty asiointirooli link
  public/modules/custom/grants_oma_asiointi/src/Plugin/Block/AsiointirooliBlock.php
Labels: UI

#1336 fix: AU-2371: fix a letter in webform actions
  conf/cmi/language/sv/webform.webform.asukasosallisuus_pienavustushake.yml
  conf/cmi/language/sv/webform.webform.asukasosallisuus_yleis_ja_toimin.yml
  conf/cmi/language/sv/webform.webform.hyte_yleisavustus.yml
  conf/cmi/language/sv/webform.webform.kasko_ip_lisa.yml
  conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_toiminta_av.yml
  conf/cmi/language/sv/webform.webform.kasvatus_ja_koulutus_yleisavustu.yml
  conf/cmi/language/sv/webform.webform.kaupunginkanslia_tyollisyysavust.yml
  conf/cmi/language/sv/webform.webform.kuva_projekti.yml
  conf/cmi/language/sv/webform.webform.kuva_toiminta.yml
  conf/cmi/language/sv/webform.webform.leiriselvitys.yml
  conf/cmi/language/sv/webform.webform.liikunta_laitosavustushakemus.yml
  conf/cmi/language/sv/webform.webform.liikunta_suunnistuskartta_avustu.yml
  conf/cmi/language/sv/webform.webform.liikunta_tapahtuma.yml
  conf/cmi/language/sv/webform.webform.liikunta_toiminta_ja_tilankaytto.yml
  conf/cmi/language/sv/webform.webform.liikunta_yleisavustushakemus.yml
  conf/cmi/language/sv/webform.webform.nuorisopalvelut_toiminta_ja_palk.yml
  conf/cmi/language/sv/webform.webform.nuorisotoiminta_projektiavustush.yml
  conf/cmi/language/sv/webform.webform.nuorlomaleir.yml
  conf/cmi/language/sv/webform.webform.nuortoimpalkka.yml
  conf/cmi/language/sv/webform.webform.taide_ja_kulttuuri_kehittamisavu.yml
  conf/cmi/language/sv/webform.webform.taide_ja_kulttuuriavustukset_tai.yml
  conf/cmi/language/sv/webform.webform.yleisavustushakemus.yml
  conf/cmi/language/sv/webform.webform.ymparistopalvelut_yleisavustus.yml
Labels: UI

#1333 fix: AU-2375: add context to string in Oma asiointi
  public/modules/custom/grants_oma_asiointi/templates/grants-oma-asiointi-front.html.twig
Labels: UI

#1335 feat: AU-2397, AU-2401, E2E, Screenshots, bug-fixes and URL logging
  e2e/playwright.config.ts
  e2e/tests/forms/private_person_48.ts
  e2e/tests/forms/private_person_64.ts
  e2e/tests/forms/registered_community_29.ts
  e2e/tests/forms/registered_community_48.ts
  e2e/tests/forms/registered_community_51.ts
  e2e/tests/forms/registered_community_52.ts
  e2e/tests/forms/registered_community_53.ts
  e2e/tests/forms/registered_community_54.ts
  e2e/tests/forms/registered_community_56.ts
  e2e/tests/forms/registered_community_57.ts
  e2e/tests/forms/registered_community_58.ts
  e2e/tests/forms/registered_community_60.ts
  e2e/tests/forms/registered_community_61.ts
  e2e/tests/forms/registered_community_62.ts
  e2e/tests/forms/registered_community_63.ts
  e2e/tests/forms/registered_community_64.ts
  e2e/tests/forms/registered_community_65.ts
  e2e/tests/forms/registered_community_66.ts
  e2e/tests/forms/registered_community_68.ts
  e2e/tests/forms/registered_community_69.ts
  e2e/tests/forms/unregistered_community_48.ts
  e2e/tests/forms/unregistered_community_62.ts
  e2e/tests/forms/unregistered_community_64.ts
  e2e/tests/forms/unregistered_community_65.ts
  e2e/tests/forms/unregistered_community_66.ts
  e2e/tests/forms/unregistered_community_69.ts
  e2e/tests/profiles/private_person.ts
  e2e/tests/profiles/registered_community.ts
  e2e/tests/profiles/unregistered_community.ts
  e2e/utils/auth_helpers.ts
  e2e/utils/copying_helpers.ts
  e2e/utils/data/application/application_data_54.ts
  e2e/utils/data/application/application_data_57.ts
  e2e/utils/data/application/application_data_58.ts
  e2e/utils/data/application/application_data_60.ts
  e2e/utils/data/application/application_data_62.ts
  e2e/utils/data/application/application_data_64.ts
  e2e/utils/data/application/application_data_68.ts
  e2e/utils/deletion_helpers.ts
  e2e/utils/field_swap_helpers.ts
  e2e/utils/form_helpers.ts
  e2e/utils/helpers.ts
  e2e/utils/validation_helpers.ts
Labels: e2e

#1334 fix: AU-2403: PHPStan Error Fixes, Part2
  public/modules/custom/grants_handler/src/Form/CopyApplicationModalForm.php
  public/modules/custom/grants_handler/src/Form/MessageForm.php
  public/modules/custom/grants_handler/src/FormLockService.php
  public/modules/custom/grants_handler/src/Plugin/Block/ApplicationTimeoutMessageBlock.php
  public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAnonBlock.php
  public/modules/custom/grants_handler/src/Plugin/Block/ServicePageAuthBlock.php
  public/modules/custom/grants_handler/src/Plugin/WebformHandler/GrantsHandler.php
  public/modules/custom/grants_handler/tests/src/Kernel/DataConversionTest.php
  public/modules/custom/grants_handler/tests/src/Kernel/WebformSubmissionNotesHelperTest.php
  public/modules/custom/grants_industries/src/Access/WebformRestrictedRouteAccessCheck.php
  public/modules/custom/grants_industries/src/Form/SettingsForm.php
  public/modules/custom/grants_mandate/src/Controller/GrantsMandateController.php
  public/modules/custom/grants_mandate/src/EventSubscriber/GrantsMandateExceptionSubscriber.php
  public/modules/custom/grants_mandate/src/Form/ApplicantMandateForm.php
  public/modules/custom/grants_menu/grants_menu.module
  public/modules/custom/grants_menu/src/ForceMenuLinkService.php
  public/modules/custom/grants_metadata/grants_metadata.module
  public/modules/custom/grants_metadata/src/AtvSchema.php
  public/modules/custom/grants_metadata/tests/src/Kernel/AtvSchemaTest.php
  public/modules/custom/grants_profile/src/Form/GrantsProfileFormRegisteredCommunity.php
  public/modules/custom/grants_webform_summation_field/src/Plugin/WebformElement/GrantsWebformSummationField.php
Labels: BE

#1340 feat: AU-2404: tests for 67
  conf/cmi/webform.webform.asukasosallisuus_yleis_ja_toimin.yml
  e2e/playwright.config.ts
  e2e/tests/forms/registered_community_67.ts
  e2e/utils/data/application/application_data_67.ts
  e2e/utils/data/application/application_data_registered_community.ts
Labels: e2e
